-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID, a.REPLY_ID, a.WRITER_ID, a.CONTENTS, DATE_FORMAT(a.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_REPLY a
LEFT JOIN USED_GOODS_BOARD b
ON a.BOARD_ID = b.BOARD_ID
WHERE b.CREATED_DATE LIKE '2022-10%'
ORDER BY CREATED_DATE, b.TITLE
