-- 코드를 입력하세요
SELECT DISTINCT(CAR.CAR_ID) as CAR_ID
FROM CAR_RENTAL_COMPANY_CAR as CAR
left join CAR_RENTAL_COMPANY_RENTAL_HISTORY as HISTORY
ON CAR.CAR_ID = HISTORY.CAR_ID
WHERE START_DATE LIKE '%-10-%' AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC
